name: AhmetCanavarVDS
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Canavarı Hazırla
      run: |
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        net user Ahmet Canavar123! /add
        net localgroup administrators Ahmet /add
    - name: Canavara Tünel Kaz (Hızlı Yol)
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: false
